# Generated by Django 6.1.1 on 2026-09-15 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpverification',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
