# Generated by Django 6.1.1 on 2026-09-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_otpverification_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetotp',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
