# Generated by Django 6.1.1 on 2026-09-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('category', models.CharField(choices=[('documentary', 'Documentary'), ('dialogue', 'Dialogue'), ('performance', 'Performance')], max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='episodes/')),
                ('image_alt', models.CharField(blank=True, help_text='Describes the image for screen readers. Leave blank if it adds nothing beyond the title.', max_length=200)),
                ('video_url', models.URLField(blank=True, help_text='Where the play button leads. The button stays disabled while this is empty.', null=True)),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
    ]
