# Generated by Django 6.1.1 on 2026-09-15 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0005_episode_category_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', help_text="Used for the card and, for the first episode, the homepage hero. Upload at least 1040x1188 so the hero's portrait crop stays sharp; smaller images still work on cards but the hero keeps its default artwork.", null=True, upload_to='episodes/', width_field='image_width'),
        ),
    ]
