# Generated by Django 6.1.1 on 2026-09-15 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0007_backfill_image_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='image',
            field=models.ImageField(blank=True, height_field='image_height', help_text='Used for the card and, for the first episode, the homepage hero. The hero crops it to portrait, so upload at least 1040x1188 to keep it sharp. Smaller images are still used; they just look soft in the hero.', null=True, upload_to='episodes/', width_field='image_width'),
        ),
    ]
