# Generated by Django 6.1.1 on 2026-09-15 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0008_alter_episode_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='hero_image',
            field=models.ImageField(blank=True, height_field='hero_image_height', help_text='Optional upright version for the homepage hero card, ideally 1040x1188. Only the first episode reaches the hero, so this is worth preparing for the one you are featuring. Without it the hero centre-crops the image above.', null=True, upload_to='episodes/hero/', verbose_name='portrait image', width_field='hero_image_width'),
        ),
        migrations.AddField(
            model_name='episode',
            name='hero_image_height',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='hero_image_width',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
