# Generated by Django 6.1.1 on 2026-09-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Episode', '0009_episode_hero_image_episode_hero_image_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='description_ur',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='episode',
            name='image_alt_ur',
            field=models.CharField(blank=True, default='', help_text='Describes the image for screen readers in Urdu. Leave blank if it adds nothing beyond the title.', max_length=200),
        ),
        migrations.AddField(
            model_name='episode',
            name='title_ur',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='episodecategory',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
