# Generated by Django 6.1.1 on 2026-09-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='country_city',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='enquiry_type',
            field=models.CharField(choices=[('general', 'General'), ('partnership', 'Partnership'), ('programme', 'Programme'), ('creative', 'Creative Collaboration'), ('media', 'Media'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
