# Generated by Django 6.1.1 on 2026-09-15 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programme',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('upcoming', 'Upcoming'), ('development', 'In Development'), ('register interest', 'Register Interest'), ('upcomming', 'Upcoming')], max_length=20),
        ),
    ]
