# Generated by Django 6.1.1 on 2026-09-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programme', '0002_alter_programme_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programme',
            options={'ordering': ['position', 'id']},
        ),
        migrations.AddField(
            model_name='programme',
            name='pillar',
            field=models.CharField(choices=[('ikhlakiat', 'Ikhlakiat'), ('idraak', 'Idraak'), ('falah', 'Falah'), ('rabta', 'Rabta'), ('sama', 'Sama')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='programme',
            name='position',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='programme',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('register_interest', 'Register Interest'), ('upcoming', 'Upcoming'), ('development', 'In Development')], max_length=20),
        ),
    ]
