# Generated by Django 6.1.1 on 2026-09-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Programme', '0004_seed_programmes'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='description_ur',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='programme',
            name='name_ur',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
